Revert "Fixes: Coverity issues (UNINIT_CTOR and FORWARD_NULL)."
This reverts commit af3ad0c3c6a9545aa94c72bfe62c10e52f3e282b.

Get the following error when building for ARM target:

/home/bifh3/harmattan-arm-unreleased.cs2009q1/work/libdui-0.19.7/src/painting/duiglrenderer.cpp: In constructor 'DuiGLRendererPrivate::DuiGLRendererPrivate()':
/home/bifh3/harmattan-arm-unreleased.cs2009q1/work/libdui-0.19.7/src/painting/duiglrenderer.cpp:193: error: expected primary-expression before '{' token
/home/bifh3/harmattan-arm-unreleased.cs2009q1/work/libdui-0.19.7/src/painting/duiglrenderer.cpp:193: error: expected `;' before '{' token
/home/bifh3/harmattan-arm-unreleased.cs2009q1/work/libdui-0.19.7/src/painting/duiglrenderer.cpp:194: error: expected primary-expression before '{' token
/home/bifh3/harmattan-arm-unreleased.cs2009q1/work/libdui-0.19.7/src/painting/duiglrenderer.cpp:194: error: expected `;' before '{' token
/home/bifh3/harmattan-arm-unreleased.cs2009q1/work/libdui-0.19.7/src/painting/duiglrenderer.cpp:195: error: expected primary-expression before '{' token
/home/bifh3/harmattan-arm-unreleased.cs2009q1/work/libdui-0.19.7/src/painting/duiglrenderer.cpp:195: error: expected `;' before '{' token