Changes: fix compilation problem with gcc 4.5
RevBy: John Tapsell, Miroslav Safr

Details:

Miroslav found that when compiling in MeeGo OBS the old code
gave the error message:

i18n/mlocale.cpp:744:1: error: 'QLocale::QLocale' names the constructor, not the type

Because this system already has gcc 4.5.