Changes: missing EOLs for gcc 4.2 eol warnings resolved as errors
Details:
 In file included from /home/builder/build/projects/libmeegotouch-n900/src/include/MSortFilterProxyModel:1,
 from /home/builder/build/projects/libmeegotouch-n900/src/corelib/widgets/mlistfilter.cpp:29:
 /home/builder/build/projects/libmeegotouch-n900/src/include/msortfilterproxymodel.h:20:54: error: no newline at end of file
 In file included from /home/builder/build/projects/libmeegotouch-n900/src/corelib/widgets/mlistfilter.cpp:29:
 /home/builder/build/projects/libmeegotouch-n900/src/include/MSortFilterProxyModel:1:35: error: no newline at end of file